// <auto-generated />
using System;
using ComponentManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ComponentManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250928140107_RelasiComponent6")]
    partial class RelasiComponent6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ComponentManagement.Domain.Entities.APL", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameBrand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PartComponentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PartComponentId");

                    b.ToTable("APLs");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.APLPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("APLId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("APLId");

                    b.ToTable("APLParts");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.ComponentActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Documentation")
                        .HasColumnType("text");

                    b.Property<string>("NeedSupport")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.ToTable("ComponentActivities");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.ComponentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewNomerLaMbung")
                        .HasColumnType("text");

                    b.Property<int?>("NewStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NewTanggalInstall")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OldNomerLaMbung")
                        .HasColumnType("text");

                    b.Property<int?>("OldStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OldTanggalInstall")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.ToTable("ComponentHistories");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.Part", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NamaPart")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.PartComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("NamaBrand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaKomponen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomerLaMbung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid?>("PartId")
                        .HasColumnType("uuid");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TanggalInstall")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoHp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.APL", b =>
                {
                    b.HasOne("ComponentManagement.Domain.Entities.PartComponent", "PartComponent")
                        .WithMany("APLs")
                        .HasForeignKey("PartComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartComponent");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.APLPart", b =>
                {
                    b.HasOne("ComponentManagement.Domain.Entities.APL", "APL")
                        .WithMany("Parts")
                        .HasForeignKey("APLId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("APL");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.ComponentActivity", b =>
                {
                    b.HasOne("ComponentManagement.Domain.Entities.PartComponent", "Component")
                        .WithMany("ComponentActivities")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.ComponentHistory", b =>
                {
                    b.HasOne("ComponentManagement.Domain.Entities.PartComponent", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.PartComponent", b =>
                {
                    b.HasOne("ComponentManagement.Domain.Entities.Part", "Part")
                        .WithMany("Components")
                        .HasForeignKey("PartId");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.APL", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.Part", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.PartComponent", b =>
                {
                    b.Navigation("APLs");

                    b.Navigation("ComponentActivities");
                });
#pragma warning restore 612, 618
        }
    }
}
