// <auto-generated />
using System;
using ComponentManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ComponentManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260208070702_Add_LifeTimeComponent")]
    partial class Add_LifeTimeComponent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ComponentManagement.Domain.Entities.APL", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameBrand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PartComponentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PartComponentId");

                    b.ToTable("APLs");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.APLPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("APLId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("APLId");

                    b.ToTable("APLParts");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.ComponentActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Documentation")
                        .HasColumnType("text");

                    b.Property<string>("NeedSupport")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.ToTable("ComponentActivities");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.ComponentCustomPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameBrand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PartComponentId")
                        .HasColumnType("uuid");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PartComponentId");

                    b.ToTable("ComponentCustomParts");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.ComponentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewNomerLaMbung")
                        .HasColumnType("text");

                    b.Property<int?>("NewStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NewTanggalInstall")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OldNomerLaMbung")
                        .HasColumnType("text");

                    b.Property<int?>("OldStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OldTanggalInstall")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.ToTable("ComponentHistories");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.ComponentLifetime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InstalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PartComponentId")
                        .HasColumnType("uuid");

                    b.Property<double>("RemainingLifetimeHm")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalLifetimeHm")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("UsedLifetimeHm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PartComponentId");

                    b.ToTable("ComponentLifetimes");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.Historical", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewCodeNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldCodeNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PartComponentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TanggalInstall")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TanggalRFU")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PartComponentId");

                    b.ToTable("Historicals");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.Part", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NamaPart")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.PartComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("NamaBrand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaKomponen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomerLaMbung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid?>("PartId")
                        .HasColumnType("uuid");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QrBase64")
                        .HasColumnType("text");

                    b.Property<string>("QrImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("QrToken")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TanggalInstall")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("UnitId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.PartComponentAPL", b =>
                {
                    b.Property<Guid>("PartComponentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("APLId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("PartComponentId", "APLId");

                    b.HasIndex("APLId");

                    b.ToTable("PartComponentAPLs");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoHp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.APL", b =>
                {
                    b.HasOne("ComponentManagement.Domain.Entities.PartComponent", "PartComponent")
                        .WithMany("APLs")
                        .HasForeignKey("PartComponentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PartComponent");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.APLPart", b =>
                {
                    b.HasOne("ComponentManagement.Domain.Entities.APL", "APL")
                        .WithMany("Parts")
                        .HasForeignKey("APLId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("APL");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.ComponentActivity", b =>
                {
                    b.HasOne("ComponentManagement.Domain.Entities.PartComponent", "Component")
                        .WithMany("ComponentActivities")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.ComponentCustomPart", b =>
                {
                    b.HasOne("ComponentManagement.Domain.Entities.PartComponent", "PartComponent")
                        .WithMany("CustomParts")
                        .HasForeignKey("PartComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartComponent");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.ComponentHistory", b =>
                {
                    b.HasOne("ComponentManagement.Domain.Entities.PartComponent", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.ComponentLifetime", b =>
                {
                    b.HasOne("ComponentManagement.Domain.Entities.PartComponent", "PartComponent")
                        .WithMany()
                        .HasForeignKey("PartComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartComponent");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.Historical", b =>
                {
                    b.HasOne("ComponentManagement.Domain.Entities.PartComponent", "PartComponent")
                        .WithMany("Historicals")
                        .HasForeignKey("PartComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartComponent");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.PartComponent", b =>
                {
                    b.HasOne("ComponentManagement.Domain.Entities.Part", "Part")
                        .WithMany("Components")
                        .HasForeignKey("PartId");

                    b.HasOne("ComponentManagement.Domain.Entities.Unit", "Unit")
                        .WithMany("PartComponents")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Part");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.PartComponentAPL", b =>
                {
                    b.HasOne("ComponentManagement.Domain.Entities.APL", "APL")
                        .WithMany("PartComponentAPLs")
                        .HasForeignKey("APLId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComponentManagement.Domain.Entities.PartComponent", "PartComponent")
                        .WithMany("PartComponentAPLs")
                        .HasForeignKey("PartComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("APL");

                    b.Navigation("PartComponent");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ComponentManagement.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.APL", b =>
                {
                    b.Navigation("PartComponentAPLs");

                    b.Navigation("Parts");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.Part", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.PartComponent", b =>
                {
                    b.Navigation("APLs");

                    b.Navigation("ComponentActivities");

                    b.Navigation("CustomParts");

                    b.Navigation("Historicals");

                    b.Navigation("PartComponentAPLs");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.Unit", b =>
                {
                    b.Navigation("PartComponents");
                });

            modelBuilder.Entity("ComponentManagement.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
